volumes:
  pg_data:
  backend_static:
  frontend_static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    container_name: backend
    build: ../backend/
    env_file: .env
    volumes:
      - backend_static:/app/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ../frontend/
    command: sh -c "cp -r /app/build/* /frontend_static/"
    volumes:
      - frontend_static:/frontend_static

  nginx:
    container_name: foodgram-proxy
    build:
      context: ..
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - backend_static:/staticfiles/admin/
      - frontend_static:/staticfiles/
      - media:/media
    depends_on:
      - backend
