volumes:
  pg_data:
  backend_static:
  frontend_static:
  media:

services:
  db:
    container_name: db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - foodgram_network
  
  backend:
    container_name: backend
    image: gurych/foodgram_backend
    ports:
      - "8080:8000"
    env_file: .env
    volumes:
      - backend_static:/app/backend_static
      - media:/app/media
    networks:
      - foodgram_network
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: gurych/foodgram_frontend
    command: sh -c "cp -r /app/build/* /frontend_static/"
    volumes:
      - frontend_static:/frontend_static
    networks:
      - foodgram_network

  nginx:
    container_name: foodgram-proxy
    image: gurych/foodgram_nginx
    ports:
      - "8001:80"
    volumes:
      - backend_static:/staticfiles/admin/
      - frontend_static:/staticfiles/
      - media:/media
    networks:
      - foodgram_network
    depends_on:
      - backend

networks:
  foodgram_network: