# Generated by Django 3.2.3 on 2025-05-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_measurement',
            new_name='measurement_unit',
        ),
    ]
